### ISSUE TITLE
sy down exits with SQL Error

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#429] opened 2015-04-01 22:55 UTC
~/piHD$ sy up
Sync up skipped, because there are remote changes.

~/piHD$ sy down
Downloading database 6/6 ...Error: Cannot persist database.
       Refer to help page using '--help'.

~/piHD$ sy down -d
<...>
1-4-15 18:32:03.470 | DownOperation   | main           | FINE :   + Contents: DatabaseVersion [header=VHzIjUorJDDzpqfLgDEL/(INsyGhiYdSsXaYALRjPf51,VHzIjUorJDDzpqfLgDEL122,mxKzitVfuURqSnMDWTyo164)/T=1427690134728, chunks=0, multiChunks=0, fileContents=0, fileHistories=10]
1-4-15 18:32:03.472 | DownOperation   | main           | INFO :   + Applying database version (INsyGhiYdSsXaYALRjPf52,VHzIjUorJDDzpqfLgDEL122,mxKzitVfuURqSnMDWTyo164)
1-4-15 18:32:03.472 | DownOperation   | main           | FINE :   + Contents: DatabaseVersion [header=INsyGhiYdSsXaYALRjPf/(INsyGhiYdSsXaYALRjPf52,VHzIjUorJDDzpqfLgDEL122,mxKzitVfuURqSnMDWTyo164)/T=1427719847305, chunks=1, multiChunks=1, fileContents=0, fileHistories=1]
1-4-15 18:32:03.473 | DownOperation   | main           | INFO :   + Applying database version (INsyGhiYdSsXaYALRjPf53,VHzIjUorJDDzpqfLgDEL122,mxKzitVfuURqSnMDWTyo164)
1-4-15 18:32:03.473 | DownOperation   | main           | FINE :   + Contents: DatabaseVersion [header=INsyGhiYdSsXaYALRjPf/(INsyGhiYdSsXaYALRjPf53,VHzIjUorJDDzpqfLgDEL122,mxKzitVfuURqSnMDWTyo164)/T=1427720262590, chunks=5, multiChunks=1, fileContents=1, fileHistories=2]
1-4-15 18:32:03.475 | DatabaseVersion | main           | SEVE : SQL Error: 
java.sql.BatchUpdateException: integrity constraint violation: foreign key no parent; SYS_FK_10210 table: MULTICHUNK_CHUNK
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
	at org.syncany.database.dao.MultiChunkSqlDao.writeMultiChunkRefs(MultiChunkSqlDao.java:81)
	at org.syncany.database.dao.MultiChunkSqlDao.writeMultiChunks(MultiChunkSqlDao.java:67)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:147)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:108)
	at org.syncany.database.SqlDatabase.writeDatabaseVersion(SqlDatabase.java:182)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersion(DownOperation.java:597)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersions(DownOperation.java:584)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:464)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:189)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)

1-4-15 18:32:11.339 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@50383c13 FAILED. 
java.lang.RuntimeException: Cannot persist database.
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:118)
	at org.syncany.database.SqlDatabase.writeDatabaseVersion(SqlDatabase.java:182)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersion(DownOperation.java:597)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersions(DownOperation.java:584)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:464)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:189)
	at org.syncany.Client.down(Client.java:128)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:55)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: java.sql.BatchUpdateException: integrity constraint violation: foreign key no parent; SYS_FK_10210 table: MULTICHUNK_CHUNK
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
	at org.syncany.database.dao.MultiChunkSqlDao.writeMultiChunkRefs(MultiChunkSqlDao.java:81)
	at org.syncany.database.dao.MultiChunkSqlDao.writeMultiChunks(MultiChunkSqlDao.java:67)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:147)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:108)
	... 11 more
Error: Cannot persist database.
       Refer to help page using '--help'.

**Comment by binwiederhier** [comment] 2015-04-01 23:12
Oh no. I thought we were past that. 

@Kudret To debug this, we'll need as much information as possible, i.e. log files in .config/syncany, the ".syncany" folders, the remote database. Otherwise, we don't stand a chance I'm afraid...

**Comment by Kudret** [comment] 2015-04-03 15:01
@pimotte 
397f3c8cc4041622c068cbeb4aee9a02bb527165 belongs to a file generated by
WORK~/piHD$ find . -type f -exec md5sum {} \; > MD5s/kudo-deb7-64-20150401-temp.md5
on my work machine.  Below is from my home machine. 

HOME~/piHD/.syncany/logs$ grep 397f3c8cc4041622c068cbeb4aee9a02bb527165 *
syncany.log.0:2-4-15 11:36:24.754 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
syncany.log.0:2-4-15 11:36:24.766 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150401-temp.md5
syncany.log.2:2-4-15 11:26:50.968 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
syncany.log.2:2-4-15 11:26:50.968 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150330-temp.md5
syncany.log.2:2-4-15 11:27:41.324 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]
syncany.log.2:2-4-15 11:27:41.324 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/fin-20150330-temp.md5

**Comment by Kudret** [comment] 2015-04-03 15:12
appears like same id is used for MD5s/fin-20150330-temp.md5 which possibly might have the same content but created on my home machine, hence different name...

**Comment by pimotte** [comment] 2015-04-03 18:25
Can you provide the .config/syncany/logs back a bit further, if you have them? The first operation involving the bad chunk is started further back then syncany.log.3

**Comment by Kudret** [comment] 2015-04-03 18:41
HOME~/.config/syncany/logs$ grep 397f3c8cc4041622c068cbeb4aee9a02bb527165 *
syncany.log.1:2-4-15 6:06:37.648 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
syncany.log.1:2-4-15 6:06:37.649 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150330-temp.md5
syncany.log.1:2-4-15 6:07:28.970 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]
syncany.log.1:2-4-15 6:07:28.970 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/fin-20150330-temp.md5
syncany.log.2:2-4-15 5:59:53.721 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
syncany.log.2:2-4-15 5:59:53.733 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150401-temp.md5

**Comment by pimotte** [comment] 2015-04-03 18:58
I'm sorry, I meant the actual (redacted) files you sent us. From the .syncany/config files we have up till .3, but the start of the "Down" that involves this file is in .4 or maybe even .5. If you could redact those and send them to us, that would be great.

**Comment by Kudret** [comment] 2015-04-03 19:23
WORK~/home/kudret$ grep 397f3c8cc4041622c068cbeb4aee9a02bb527165 .config/syncany/logs/* piHD/.syncany/logs/* --color
.config/syncany/logs/syncany.log.1:1-4-15 7:24:17.748 | Indexer         | WR/piHD        | INFO :    * Added file version:    FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.2:30-3-15 8:52:29.584 | Indexer         | WR/piHD        | INFO :    * Added file version:    FileVersion [version=1, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=NEW, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Mon Mar 30 08:52:29 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.2:30-3-15 9:02:52.588 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=1, path=MD5s/fin-20150330-temp.md5, type=FILE, status=NEW, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Mon Mar 30 08:57:42 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.2:30-3-15 9:02:52.588 | FileSystemActio | WR/piHD        | INFO :      -> (2) Deleted: Local file does NOT exist, but it should, winning version not known: FileVersion [version=1, path=MD5s/fin-20150330-temp.md5, type=FILE, status=NEW, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Mon Mar 30 08:57:42 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-] AND /local/kudo/Personal/piHD/MD5s/fin-20150330-temp.md5
.config/syncany/logs/syncany.log.2:30-3-15 9:02:52.588 | FileSystemActio | WR/piHD        | INFO :      -> NewFileSystemAction [file1=null, file2=FileVersion [version=1, path=MD5s/fin-20150330-temp.md5, type=FILE, status=NEW, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Mon Mar 30 08:57:42 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]]
.config/syncany/logs/syncany.log.2:30-3-15 9:03:08.727 | FileSystemActio | WR/piHD        | INFO :    + NewFileSystemAction [file1=null, file2=FileVersion [version=1, path=MD5s/fin-20150330-temp.md5, type=FILE, status=NEW, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Mon Mar 30 08:57:42 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]]
.config/syncany/logs/syncany.log.2:30-3-15 9:07:41.479 | Indexer         | WR/piHD        | INFO :    * Added file version:    FileVersion [version=1, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=NEW, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Mon Mar 30 09:07:41 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]

**Comment by Kudret** [comment] 2015-04-03 19:26
LAPTOP~/home/kudret$ grep 397f3c8cc4041622c068cbeb4aee9a02bb527165 .config/syncany/logs/* piHD/.syncany/logs/*
.config/syncany/logs/syncany.log.0:1-4-15 18:03:11.107 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.0:1-4-15 18:03:11.107 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150401-temp.md5
.config/syncany/logs/syncany.log.2:1-4-15 18:01:03.712 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.2:1-4-15 18:01:03.712 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150330-temp.md5
.config/syncany/logs/syncany.log.2:1-4-15 18:01:20.261 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.2:1-4-15 18:01:20.261 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/fin-20150330-temp.md5
.config/syncany/logs/syncany.log.3:1-4-15 8:11:41.695 | FileSystemActio | WR/piHD        | INFO :     with winning version   : FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
.config/syncany/logs/syncany.log.3:1-4-15 8:11:41.696 | FileSystemActio | WR/piHD        | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150401-temp.md5
piHD/.syncany/logs/syncany.log.0:1-4-15 23:05:51.909 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
piHD/.syncany/logs/syncany.log.0:1-4-15 23:05:51.909 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150401-temp.md5
piHD/.syncany/logs/syncany.log.2:1-4-15 23:04:24.724 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
piHD/.syncany/logs/syncany.log.2:1-4-15 23:04:24.724 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/kudo-deb7-64-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:49:53 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150330-temp.md5
piHD/.syncany/logs/syncany.log.2:1-4-15 23:04:31.542 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-]
piHD/.syncany/logs/syncany.log.2:1-4-15 23:04:31.542 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=2, path=MD5s/fin-20150330-temp.md5, type=FILE, status=DELETED, size=148, lastModified=Mon Mar 30 08:53:15 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 00:18:45 EDT 2015, posixPermissions=rw-rw-r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/fin-20150330-temp.md5
piHD/.syncany/logs/syncany.log.3:1-4-15 23:01:24.873 | FileSystemActio | main           | INFO :     with winning version   : FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-]
piHD/.syncany/logs/syncany.log.3:1-4-15 23:01:24.874 | FileSystemActio | main           | INFO :      -> (1) Equals: Nothing to do, winning version equals winning file: FileVersion [version=1, path=MD5s/kudo-deb7-64-20150401-temp.md5, type=FILE, status=NEW, size=148, lastModified=Wed Apr 01 07:18:52 EDT 2015, linkTarget=null, checksum=397f3c8cc4041622c068cbeb4aee9a02bb527165, updated=Wed Apr 01 07:24:17 EDT 2015, posixPermissions=rw-r--r--, dosAttributes=--a-] AND /home/kudret/piHD/MD5s/kudo-deb7-64-20150401-temp.md5

**Comment by pimotte** [comment] 2015-04-04 09:00
I have sorted these logs by timestamp, are all of your machines in the same timezone? (Won't be posting it here to reduce lengthiness, but let me know if anyone would like to have this for debugging.)

Can you specify how you generate and delete these files? (ie. manually, crontabs, do you delete on multiple computers)

**Comment by pimotte** [comment] 2015-04-04 14:08
I decided to do some fuzzy testing to try to reproduce this. This at least fails with an SQLException, so I'm guessing it's getting closer to the key issue.

Pushed at: https://github.com/syncany/syncany/tree/bugfix/issue429-fuzzy

**Comment by Asherehsa** [comment] 2015-04-06 21:54
I'm also getting "Error: Cannot persist database." Here's a log, hope it's helpful! 
https://gist.github.com/Asherehsa/f4565c99788d4e835bf9

**Comment by pimotte** [comment] 2015-04-09 20:17
@Asherehsa I completely forgot about you posting this here. It looks to be a separate issue, but these are really hard to debug.

Could you email us (team@syncany.org) all your logs and database files (from the repo, the databases folder)? Feel free to anonimize them if there's sensitive information about the metadata.

After discussion with @Kudret, I've decided to close this issue, since I suspect #433 has fixed this, but there is not enough information to verify or reliably reproduce this.

**Closed** 2015-04-09 20:17 UTC
Labels: prio:high, status:help-needed, type:bug, what:core
