### ISSUE TITLE
Auth Fail with SFTP plugin and password authentication

### ISSUE THREAD

**Issue by apoggio** [syncany/syncany#440] opened 2015-04-14 06:50 UTC
Creating a new repository with the SFTP plugin using password authentication fails.  The error shows as:
org.syncany.plugins.transfer.StorageException: com.jcraft.jsch.JSchException: Auth fail

I tested the host, username, and password using sftp on the command line, so I know they are correct.

**Comment by cr0** [comment] 2015-04-14 11:56
Could you please provide a full debug log here. Make sure to include Syncany version and plugin version.

It might be that the used authentication method is unsupported by JSCH.

**Comment by apoggio** [comment] 2015-04-14 17:01
Hi Christian,

Thanks for the reply.  Here's the info you requested:
Syncany v0.4.4-alpha
Syncany GUI Plugin v0.4.4-alpha
Syncany SFTP Plugin v0.4.5-alpha

Initializing repo for folder /Users/andy/SyncAny ...ERROR

Unable to initialize folder (code: 502)
Testing the remote storage failed.

- Was the connection successful: NO
- Files can be created: NO
- Files can be written to: NO
- The target folder/repo exists: NO

Detailed test error:

org.syncany.plugins.transfer.StorageException: com.jcraft.jsch.JSchException: Auth fail
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:168)
	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
	at org.syncany.operations.init.InitOperation.performRepoTest(InitOperation.java:164)
	at org.syncany.operations.init.InitOperation.execute(InitOperation.java:89)
	at org.syncany.operations.daemon.messages.InitManagementRequestHandler$1.run(InitManagementRequestHandler.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:160)
	... 5 more

Using tcpdump, I can see that communication with the remote host is taking place.  Since it's encrypted, I can't tell what has been communicated.

--andy

**Comment by cr0** [comment] 2015-04-15 13:08
Anything in the server log? Perhaps you can compare the supported authentication mechanism to the ones supported by JSch. You can find them here: http://www.jcraft.com/jsch/README

I recall that we had a similar case where the server did not support any of JSch authentication methods.

**Comment by apoggio** [comment] 2015-04-15 18:13
The server log shows:
4/15/15 11:11:14.909 AM sshd[96418]: error: Received disconnect from ....: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]

**Comment by apoggio** [comment] 2015-04-15 18:15
The JSch README says that password authentication is supported.  The server supports password authentication as that is what I use on the command line to invoke sftp.

**Comment by Hazmit** [comment] 2015-05-05 19:05
I can second the issues with the SFTP plugin. I'm having the same problems and can't get passed it to use Syncany. Bumping this for attention. If something is needed for debug from me I'm happy to provide.

**Comment by Querijn** [comment] 2015-05-13 08:05
Confirming that I am having the same issue. SFTP, one.com ssh, login details work in Filezilla.

**Comment by holleboom** [comment] 2015-05-13 08:07
Confirming that I am having the same issue as well with Amazon S3.

**Comment by cr0** [comment] 2015-05-13 08:40
@binwiederhier Since you have an Amazon S3 Account, could you please verify that it breaks with the current sftp plugin?

@holleboom Any reason why you accessing S3 through sftp and not with our dedicated S3 plugin?

**Comment by holleboom** [comment] 2015-05-13 08:41
@holleboom Any reason why you accessing S3 through sftp and not with our dedicated S3 plugin?

Ah sorry for the confusion, I'm getting the same error with the S3 plugin.

**Comment by pimotte** [comment] 2015-05-13 09:21
@holleboom Are you getting the exact same error? I highly doubt that, since we don't use Jsch in the s3 plugin. Could you open a new issue with a complete output of `syncany init -d` with any authorization details in the logs removed?

For the SFTP users @Querijn @apoggio @Hazmit, I have updated the sftp plugin. Can you try if it works with the 0.4.5-release of syncany, and the bleeding edge version of the plugin (installable by: `syncany plugin install sftp --snapshot`, or by compiling syncany-plugin-sftp/develop). Note that the current Syncany develop branch is broken with the bleeding edge plugin, so you can't use that until we fix another issue.

**Comment by pimotte** [comment] 2015-05-13 10:52
The plugin should now also function with the develop branch of the main project, so I'm looking forward to any testing results. If it still fails, complete logs (with any authentication details edited out) are really useful to investigate further.

**Comment by binwiederhier** [comment] 2015-05-14 22:12
@pimotte @cr0 
I feel there have been lots of SFTP and S3 failures lately. Do you guys need me to get on board and/or test stuff? I must admit I have barely been able to keep up with this and the other threads.

**Comment by pimotte** [comment] 2015-05-15 07:26
The S3 failure seems to be just @holleboom.

The SFTP one is big. Multiple users have reported this and #410 contains a ton of relevant details. 

However, I have not been able to reproduce it and I suspect it's not "just" a server configuration issue as I initially suspected.

**Comment by pimotte** [comment] 2015-06-16 10:16
Closed by https://github.com/syncany/syncany-plugin-sftp/pull/5. For more information, see #410.

If this issue persists for any of you with the current snapshot release (`syncany plugin install sftp --snapshot`), please open a new issue with enough information for us to reproduce and/or debug it.

**Closed** 2015-06-20 22:42 UTC
Labels: prio:high, type:bug, what:plugin
