### ISSUE TITLE
sy plugin install Error: java.lang.IllegalAccessException Can not set static final boolean field

### ISSUE THREAD

**Issue by NK74** [syncany/syncany#597] opened 2017-01-10 13:26 UTC
Issue with S3 plugin

> sy plugin install s3
> Installing plugin from https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar ...Error: java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean
>         Refer to help page using '--help'.
> 

Same with FTP
> sy plugin install ftp
> Installing plugin from https://get.syncany.org/dist/plugins/releases/ftp/syncany-plugin-ftp-0.4.0-alpha.jar ...Error: java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean
>        Refer to help page using '--help'.

Debug :

```
sy plugin install s3 -d
debug
Application version: 0.4.7-alpha
10-1-17 14:24:36.328 | CommandLineClie | main           | INFO : Application version: 0.4.7-alpha
10-1-17 14:24:36.484 | Plugins         | main           | INFO : - org.syncany.plugins.local.LocalTransferPlugin
10-1-17 14:24:36.486 | Plugins         | main           | WARN : Could not load plugin (1): s3 (not found or issues with loading)
10-1-17 14:24:36.487 | PluginOperation | main           | INFO : Plugin 's3' not installed. Okay!
10-1-17 14:24:36.489 | PluginOperation | main           | INFO : Querying https://api.syncany.org/v3/plugins/list?appVersion=0.4.7-alpha&snapshots=false&pluginId=s3&os=windows&arch=x86 ...
10-1-17 14:24:36.490 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event ConnectToHostExternalEvent (org.syncany.operations.daemon.messages.ConnectToHostExternalEvent@874448) ...
Connecting to api.syncany.org ...10-1-17 14:24:36.673 | sun.net.www.pro | main           | FINE : ProxySelector Request for https://api.syncany.org/v3/plugins/list?appVersion=0.4.7-alpha&snapshots=false&pluginId=s3&os=windows&arch=x86
10-1-17 14:24:36.677 | sun.net.www.pro | main           | FINE : Looking for HttpClient for URL https://api.syncany.org/v3/plugins/list?appVersion=0.4.7-alpha&snapshots=false&pluginId=s3&os=windows&arch=x86 and proxy value of DIRECT
10-1-17 14:24:36.677 | sun.net.www.pro | main           | FINE : Creating new HttpsClient with url:https://api.syncany.org/v3/plugins/list?appVersion=0.4.7-alpha&snapshots=false&pluginId=s3&os=windows&arch=x86 and proxy:DIRECT with connect timeout:2000
10-1-17 14:24:36.905 | sun.net.www.pro | main           | FINE : Proxy used: DIRECT
10-1-17 14:24:37.084 | sun.net.www.pro | main           | FINE : sun.net.www.MessageHeader@6201975 pairs: {GET /v3/plugins/list?appVersion=0.4.7-alpha&snapshots=false&pluginId=s3&os=windows&arch=x86 HTTP/1.1: null}{User-Agent: Java/1.8.0_111}{Host: api.syncany.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
10-1-17 14:24:37.135 | sun.net.www.pro | main           | FINE : KeepAlive stream used: https://api.syncany.org/v3/plugins/list?appVersion=0.4.7-alpha&snapshots=false&pluginId=s3&os=windows&arch=x86
10-1-17 14:24:37.136 | sun.net.www.pro | main           | FINE : sun.net.www.MessageHeader@eda5c98 pairs: {null: HTTP/1.1 200 OK}{Date: Tue, 10 Jan 2017 13:24:37 GMT}{Server: Apache}{Vary: Accept-Encoding}{Content-Length: 997}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}{Content-Type: application/xml}
10-1-17 14:24:37.139 | PluginOperation | main           | INFO : Response from api.syncany.org: <?xml version="1.0"?><pluginListResponse xmlns="http://syncany.org/plugins/1/list">    <code>200</code>    <message>OK</message>    <plugins>        <pluginInfo>            <pluginId>s3</pluginId>            <pluginName>Amazon S3</pluginName>            <pluginVersion>0.4.6-alpha</pluginVersion>            <pluginOperatingSystem>all</pluginOperatingSystem>            <pluginArchitecture>all</pluginArchitecture>            <pluginDate>Sat Jul 11 12:48:04 UTC 2015</pluginDate>            <pluginAppMinVersion>0.4.6-alpha</pluginAppMinVersion>            <pluginRelease>true</pluginRelease>            <pluginConflictsWith></pluginConflictsWith>            <pluginThirdParty>false</pluginThirdParty>            <downloadUrl>https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar</downloadUrl>            <sha256sum>6e4e155c8bcd6700a29696c9529fe72e7b4453343d73b0e10384a116510dc980</sha256sum>        </pluginInfo>    </plugins></pluginListResponse>
10-1-17 14:24:37.158 | PluginOperation | main           | INFO : Checking plugin compatibility:
10-1-17 14:24:37.159 | PluginOperation | main           | INFO : - Application version:             0.4.7-alpha(0.4.7-alpha)
10-1-17 14:24:37.161 | PluginOperation | main           | INFO : - Plugin min. application version: 0.4.6-alpha(0.4.6-alpha)
10-1-17 14:24:37.162 | PluginOperation | main           | INFO : Checking for conflicting plugins.
10-1-17 14:24:37.163 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event PluginInstallExternalEvent (org.syncany.operations.daemon.messages.PluginInstallExternalEvent@1b0f2b9) ...
Installing plugin from https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar ...10-1-17 14:24:37.164 | PluginOperation | main           | INFO : Querying https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar ...
10-1-17 14:24:37.166 | PluginOperation | main           | INFO : Downloading to C:\Users\VALENT~1.PAR\AppData\Local\Temp\syncany-plugin5693831531874074096tmp ...
10-1-17 14:24:37.167 | sun.net.www.pro | main           | FINE : ProxySelector Request for https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar
10-1-17 14:24:37.167 | sun.net.www.pro | main           | FINE : Looking for HttpClient for URL https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar and proxy value of DIRECT
10-1-17 14:24:37.168 | sun.net.www.pro | main           | FINE : Creating new HttpsClient with url:https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar and proxy:DIRECT with connect timeout:2000
10-1-17 14:24:37.225 | sun.net.www.pro | main           | FINE : Proxy used: DIRECT
10-1-17 14:24:37.365 | sun.net.www.pro | main           | FINE : sun.net.www.MessageHeader@76a9af5 pairs: {GET /dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_111}{Host: get.syncany.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
10-1-17 14:24:37.413 | sun.net.www.pro | main           | FINE : KeepAlive stream used: https://get.syncany.org/dist/plugins/releases/s3/syncany-plugin-s3-0.4.6-alpha.jar
10-1-17 14:24:37.413 | sun.net.www.pro | main           | FINE : sun.net.www.MessageHeader@c7ffd310 pairs: {null: HTTP/1.1 200 OK}{Date: Tue, 10 Jan 2017 13:24:37 GMT}{Server: Apache}{Last-Modified: Sat, 11 Jul 2015 12:48:18 GMT}{ETag: "48b266-51a98e717c880"}{Accept-Ranges: bytes}{Content-Length: 4764262}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}{Content-Type: application/java-archive}
```

**Comment by streckus** [comment] 2017-01-11 15:22
I think this is a duplicate of #595

**Comment by pimotte** [comment] 2017-01-12 16:50
I think so too. A fix should be available as a snapshot: https://get.syncany.org/dist/snapshots/
(Any identified as 1612241048.gitc204ccd should work).

In #595 I promised to make a release once someone can confirm this snapshot works.

**Comment by NK74** [comment] 2017-01-13 12:46
I'll try in few day 👍

**Comment by pimotte** [comment] 2017-01-16 14:56
0.4.8 should fix this.

**Closed by pimotte** 2017-01-16 14:56 UTC
