### ISSUE TITLE
On Windows 10 when using a high DPI monitor the GUI is unusable

### ISSUE THREAD

**Issue by megheaiulian** [syncany/syncany#527] opened 2015-11-03 09:36 UTC
A example:
![Syncany](https://www.dropbox.com/s/srxaqcg7d2wdkgw/2015-11-03%2011_34_19-Calendar.png?dl=1)

**Comment by binwiederhier** [comment] 2015-11-08 00:30
This is a duplicate of https://github.com/syncany/syncany/issues/475

**Closed by binwiederhier** 2015-11-08 00:30 UTC
