### ISSUE TITLE
unable to init/connect password-authenticated sftp

### ISSUE THREAD

**Issue by vonronne** [syncany/syncany#410] opened 2015-03-12 20:21 UTC
I've been unable to use "sy init" to set up a local directory to synchronize with a password-authenticated sftp repository.  (jcsh throws an auth error when trying to validate the connection information.)   I am using syncany/sftp 0.4.3-alpha, but I also tried replacing sftp with the snapshot release (which seemed to have some related code changes) but that didn't help.

Public key authentication did work, however, and I was able to use that to set up a repository / local directory and then manually edit the .syncany/config (removing the private key and replacing the encrypted private key password with my unencrypted sftp account password) to produce a working local directory that would synchronize with the repository using password authentication.
 
I, then, tried to export that (working) configuration into a URL using sy genlink and put that into sy connect. This resulted in what appears to be the same error (with the same stack trace, etc.) as the "sy init".  Here's a transcript of the "sy connect" attempt (with personal keys/information censored):

    sy -d connect syncany://2/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    debug
    Application version: 0.4.3-alpha
    12-3-15 1:21:16.298 | CommandLineClie | main           | INFO : Application version: 0.4.3-alpha
    12-3-15 1:21:16.302 | PidFileUtil     | main           | INFO : isProcessRunningUnixLike(521) returned 0, process running = true
    12-3-15 1:21:16.501 | ConnectOperatio | main           | INFO : 
    12-3-15 1:21:16.501 | ConnectOperatio | main           | INFO : Running 'Connect'
    12-3-15 1:21:16.501 | ConnectOperatio | main           | INFO : --------------------------------------------
    12-3-15 1:21:16.501 | ConnectOperatio | main           | INFO : Creating config TO from link: syncany://2/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ...
    12-3-15 1:21:16.504 | ApplicationLink | main           | INFO : - Master salt: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:21:16.504 | ApplicationLink | main           | INFO : - Encrypted plugin settings: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:21:16.507 | ConnectOperatio | main           | INFO :  - Link is encrypted. Asking for password.
    
    Password: 
    12-3-15 1:21:28.420 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event ShowMessageExternalEvent (org.syncany.operations.daemon.messages.ShowMessageExternalEvent@485bee66) ...
    
    Creating master key from password (this might take a while) ...
    12-3-15 1:21:28.425 | CipherUtil      | main           | FINE : - Creating secret key using PBKDF2WithHmacSHA1 with 1,000,000 rounds, key size 512 bit ...
    12-3-15 1:21:32.897 | CipherSession   | main           | FINE : - Created NEW READ secret key HmacSHA256, and added to cache, with salt XXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:21:32.913 | CipherSession   | main           | FINE : - Created NEW READ secret key AES, and added to cache, with salt XXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:21:32.919 | CipherSession   | main           | FINE : - Created NEW READ secret key Twofish, and added to cache, with salt XXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:21:33.057 | Plugins         | main           | INFO : - org.syncany.plugins.gui.GuiPlugin
    12-3-15 1:21:33.058 | Plugins         | main           | INFO : - org.syncany.plugins.local.LocalTransferPlugin
    12-3-15 1:21:33.059 | Plugins         | main           | INFO : - org.syncany.plugins.sftp.SftpTransferPlugin
    12-3-15 1:21:33.074 | ApplicationLink | main           | INFO : (Decrypted) link contains: sftp -- <sftpTransferSettings type="sftp"><hostname>XXXXXXXXXXXXXXXXXXX</hostname><username>XXXXXXXXXXXX</username><password>XXXXXXXXXXXXXXXXXXXX</password><path>/X/X</path><port>22</port></sftpTransferSettings>
    12-3-15 1:21:33.075 | org.syncany.plu | main           | FINE : Validating required fields
    12-3-15 1:21:33.083 | AbstractTransfe | main           | INFO : Performing storage test TM.test() ...
    12-3-15 1:21:33.083 | AbstractTransfe | main           | INFO : - Running connect() ...
    12-3-15 1:21:33.083 | SftpTransferMan | main           | INFO : SFTP client connecting to XXXXXXXXXXXXXXXXXXX:22 ...
    12-3-15 1:21:33.378 | SftpTransferMan | main           | WARN : SFTP client connection failed.
    com.jcraft.jsch.JSchException: Auth fail
    	at com.jcraft.jsch.Session.connect(Session.java:512)
    	at com.jcraft.jsch.Session.connect(Session.java:183)
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
    	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
    	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:303)
    	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:112)
    	at org.syncany.Client.connect(Client.java:175)
    	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
    	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
    	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
    	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
    	at org.syncany.Syncany.main(Syncany.java:55)
    12-3-15 1:21:33.379 | AbstractTransfe | main           | INFO : -> Testing storage failed. Returning StorageTestResult [targetExists=false, targetCanConnect=false, targetCanCreate=false, targetCanWrite=false, repoFileExists=false]
    org.syncany.plugins.transfer.StorageException: com.jcraft.jsch.JSchException: Auth fail
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
    	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
    	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:303)
    	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:112)
    	at org.syncany.Client.connect(Client.java:175)
    	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
    	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
    	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
    	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
    	at org.syncany.Syncany.main(Syncany.java:55)
    Caused by: com.jcraft.jsch.JSchException: Auth fail
    	at com.jcraft.jsch.Session.connect(Session.java:512)
    	at com.jcraft.jsch.Session.connect(Session.java:183)
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
    	... 9 more
    12-3-15 1:21:33.379 | ConnectOperatio | main           | INFO : Storage test result ist StorageTestResult [targetExists=false, targetCanConnect=false, targetCanCreate=false, targetCanWrite=false, repoFileExists=false]
    12-3-15 1:21:33.379 | ConnectOperatio | main           | INFO : --> NOT OKAY: Invalid target/repo state. Operation cannot be continued.
    12-3-15 1:21:33.380 | ConnectOperatio | main           | INFO : - Connecting to the repo failed, repo already exists or cannot be created: NOK_TEST_FAILED
    
    ERROR: Cannot connect to the repository, because the connection to the storage backend failed.
           Possible reasons for this could be connectivity issues (are you connect to the Internet?),
           or invalid user credentials (are username/password valid?).
    
    Details:
    - Target connect success: false
    - Target exists:          false
    - Target creatable:       false
    - Target writable:        false
    - Repo file exists:       false
    
    Error message (see log file for details):
      org.syncany.plugins.transfer.StorageException: com.jcraft.jsch.JSchException: Auth fail
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
    	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
    	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:303)
    	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:112)
    	at org.syncany.Client.connect(Client.java:175)
    	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
    	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
    	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
    	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
    	at org.syncany.Syncany.main(Syncany.java:55)
    Caused by: com.jcraft.jsch.JSchException: Auth fail
    	at com.jcraft.jsch.Session.connect(Session.java:512)
    	at com.jcraft.jsch.Session.connect(Session.java:183)
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
    	... 9 more
    
    Connection failure
    
    Would you change the settings and retry the connection (y/n)? y
    
    Connection details for sftp connection:
    - Hostname (XXXXXXXXXXXXXXXXXXX): 
    - Username (XXXXXXXXXXXX): 
    - Password (***, not displayed): 
    - Private Key (optional, default is none): 
    - Path (/X/X): 
    - Port (22): 
    12-3-15 1:22:01.076 | org.syncany.plu | main           | FINE : Validating required fields
    12-3-15 1:22:01.081 | org.syncany.cli | main           | INFO : Settings are SftpTransferSettings[hostname=XXXXXXXXXXXXXXXXXXX:22, username=XXXXXXXXXXXX, path=/X/X]
    12-3-15 1:22:01.081 | ConnectOperatio | main           | INFO : 
    12-3-15 1:22:01.082 | ConnectOperatio | main           | INFO : Running 'Connect'
    12-3-15 1:22:01.083 | ConnectOperatio | main           | INFO : --------------------------------------------
    12-3-15 1:22:01.084 | ConnectOperatio | main           | INFO : Creating config TO from link: syncany://2/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ...
    12-3-15 1:22:01.086 | ApplicationLink | main           | INFO : - Master salt: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:22:01.086 | ApplicationLink | main           | INFO : - Encrypted plugin settings: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:22:01.087 | ConnectOperatio | main           | INFO :  - Link is encrypted. Asking for password.
    
    Password: 
    12-3-15 1:22:38.556 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event ShowMessageExternalEvent (org.syncany.operations.daemon.messages.ShowMessageExternalEvent@f6096f9) ...
    
    Creating master key from password (this might take a while) ...
    12-3-15 1:22:38.557 | CipherUtil      | main           | FINE : - Creating secret key using PBKDF2WithHmacSHA1 with 1,000,000 rounds, key size 512 bit ...
    12-3-15 1:22:43.048 | CipherSession   | main           | FINE : - Created NEW READ secret key HmacSHA256, and added to cache, with salt XXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:22:43.049 | CipherSession   | main           | FINE : - Created NEW READ secret key AES, and added to cache, with salt XXXXXXXXXXXXXXXXXXXXXXXX
    12-3-15 1:22:43.050 | CipherSession   | main           | FINE : - Created NEW READ secret key Twofish, and added to cache, with salt 6627ab117eba614d424880ee
    12-3-15 1:22:43.054 | ApplicationLink | main           | INFO : (Decrypted) link contains: sftp -- <sftpTransferSettings type="sftp"><hostname>XXXXXXXXXXXXXXXXXXX</hostname><username>XXXXXXXXXXXX</username><password>XXXXXXXXXXXXXXXXXXXX</password><path>/X/X</path><port>22</port></sftpTransferSettings>
    12-3-15 1:22:43.054 | org.syncany.plu | main           | FINE : Validating required fields
    12-3-15 1:22:43.056 | AbstractTransfe | main           | INFO : Performing storage test TM.test() ...
    12-3-15 1:22:43.056 | AbstractTransfe | main           | INFO : - Running connect() ...
    12-3-15 1:22:43.056 | SftpTransferMan | main           | INFO : SFTP client connecting to XXXXXXXXXXXXXXXXXXX:22 ...
    12-3-15 1:22:43.270 | SftpTransferMan | main           | WARN : SFTP client connection failed.
    com.jcraft.jsch.JSchException: Auth fail
    	at com.jcraft.jsch.Session.connect(Session.java:512)
    	at com.jcraft.jsch.Session.connect(Session.java:183)
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
    	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
    	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:303)
    	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:112)
    	at org.syncany.Client.connect(Client.java:175)
    	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
    	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
    	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
    	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
    	at org.syncany.Syncany.main(Syncany.java:55)
    12-3-15 1:22:43.270 | AbstractTransfe | main           | INFO : -> Testing storage failed. Returning StorageTestResult [targetExists=false, targetCanConnect=false, targetCanCreate=false, targetCanWrite=false, repoFileExists=false]
    org.syncany.plugins.transfer.StorageException: com.jcraft.jsch.JSchException: Auth fail
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
    	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
    	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:303)
    	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:112)
    	at org.syncany.Client.connect(Client.java:175)
    	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
    	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
    	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
    	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
    	at org.syncany.Syncany.main(Syncany.java:55)
    Caused by: com.jcraft.jsch.JSchException: Auth fail
    	at com.jcraft.jsch.Session.connect(Session.java:512)
    	at com.jcraft.jsch.Session.connect(Session.java:183)
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
    	... 9 more
    12-3-15 1:22:43.271 | ConnectOperatio | main           | INFO : Storage test result ist StorageTestResult [targetExists=false, targetCanConnect=false, targetCanCreate=false, targetCanWrite=false, repoFileExists=false]
    12-3-15 1:22:43.271 | ConnectOperatio | main           | INFO : --> NOT OKAY: Invalid target/repo state. Operation cannot be continued.
    12-3-15 1:22:43.271 | ConnectOperatio | main           | INFO : - Connecting to the repo failed, repo already exists or cannot be created: NOK_TEST_FAILED
    
    ERROR: Cannot connect to the repository, because the connection to the storage backend failed.
           Possible reasons for this could be connectivity issues (are you connect to the Internet?),
           or invalid user credentials (are username/password valid?).
    
    Details:
    - Target connect success: false
    - Target exists:          false
    - Target creatable:       false
    - Target writable:        false
    - Repo file exists:       false
    
    Error message (see log file for details):
      org.syncany.plugins.transfer.StorageException: com.jcraft.jsch.JSchException: Auth fail
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:162)
    	at org.syncany.plugins.transfer.AbstractTransferManager.test(AbstractTransferManager.java:73)
    	at org.syncany.operations.init.ConnectOperation.performRepoTest(ConnectOperation.java:303)
    	at org.syncany.operations.init.ConnectOperation.execute(ConnectOperation.java:112)
    	at org.syncany.Client.connect(Client.java:175)
    	at org.syncany.cli.ConnectCommand.execute(ConnectCommand.java:60)
    	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
    	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
    	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
    	at org.syncany.Syncany.main(Syncany.java:55)
    Caused by: com.jcraft.jsch.JSchException: Auth fail
    	at com.jcraft.jsch.Session.connect(Session.java:512)
    	at com.jcraft.jsch.Session.connect(Session.java:183)
    	at org.syncany.plugins.sftp.SftpTransferManager.connect(SftpTransferManager.java:154)
    	... 9 more
    
    Connection failure
    
    Would you change the settings and retry the connection (y/n)? n

**Comment by pimotte** [comment] 2015-05-15 07:29
So many apologies for missing this. #440 has multiple users reporting the same issue, but in less detail. The core team has been unable to reproduce this so far. Does this issue still occur for you on the current syncany release with either the 0.4.5 release of the sftp plugin or the snapshot?

**Comment by vonronne** [comment] 2015-05-19 05:08
I still get the same auth error attempting to do an "sy init" with 0.4.5 from http://archive.syncany.org/apt/release/.

**Comment by pimotte** [comment] 2015-05-19 06:27
What do you have as the server OS/ssh-daemon? Can you check the server ssh logs to see if that yields more details as to why there is an auth failure?

**Comment by vonronne** [comment] 2015-05-20 03:41
I'm using Ubuntu 14.04 with openssh 6.6p1.  The server is set up to use "ChallengeResponseAuthentication" with pam.  The user account I'm connecting too has a chroot, and a "ForceCommand internal-sftp" (but since it never gets through authentication, I don't think those are the issue).  The account has a simple password, but other accounts on the machine require two-factor authentication.  

OK, I've compared the log produced when logging into the account manually (using sftp) and through "sy init".  The manual sftp login succeeds using after doing a "userauth-request ... method none [preauth]", a "userauth-request method publickey [preauuth]",and a "userauth-request method method keyboard-interactive [preauth]" leading to an "Accepted keyboard-interactive/pam".  When I use "sy init", however, the process is truncated.  It does the first "none" request, but instead of doing a second userauth request it gives the error "May 19 22:04:11 XXXX sshd[8629]: error: Received disconnect from XXX.XXX.XXX.XXX: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]".

**Comment by pimotte** [comment] 2015-05-20 14:44
I've been unable to reproduce the issue so far. However, I do have a hunch why it goes wrong.

In the SftpTransferManager, we do not provide the password/passphrase to our SftpUserInfo, assuming Jsch will take them out of the other security parameters. Idea for possible fix: Supply the password/passphrase to the SftpUserInfo, return true to the prompt methods if the values passed in the constructor are not null and return those on the getters if called. @binwiederhier/@cr0, opinions before I do something stupid?

**Comment by pimotte** [comment] 2015-05-30 09:12
FYI: I haven't forgotten about this, and it will be the first thing I do when I get some time to work on Syncany, which will be in about two weeks.

**Comment by pimotte** [comment] 2015-06-12 18:21
I've written what hopefully should be a [fix](https://github.com/syncany/syncany-plugin-sftp/tree/bugfix/interactiveness). If you could install the build I've made available on the following webdav repo and try it out, that would be great:)

syncany://2/3k8o9weF4BtSKHA6RBd6CrQz97QWZvyq45idsKvAjmafZuGL1Pz43D5puVRWtjFry5uHcA9r4YVYVjq1immou86h/4XSk9Zn2dA8dEUMR3XqbGDARXj1vRXmA2tFpjAD1dyT3nv9EMLzmuyi6jdRpH1taj9bCLRok8HF4BntS99ekU5XpQqYbqNWcwecf5NpfP5PG4n6LieTXAQkSTueN7BAbxzs6auB28W2tmpatzg5VCoWQh5Jk3VA9JTkqEtVYHTvc6PVysK4v6sproZ6qUPpxHmk3GxqARLaaHFpTL5h6xMMqfh4FTXEJZwqzFNW7E1rSGhbGpzxGAB9tfhJdDL6RyVHDV1GxwchQpBuZqpfd5FJasgJmnZkZQEykzHpPK6L5Cy4sZMpHYivcfBTvP9CsgSg7Z8v4VFBNFpj

**Comment by vonronne** [comment] 2015-06-12 22:03
I grabbed the proposed fix from git and built a "0.4.6-alpha+SNAPSHOT.1506122002.gitdf0aaa4" sftp plugin (./gradlew pluginjar) and installed it into syncany (it shows up as the SNAPSHOT in sy plugin list).  Unfortunately, it doesn't seem to help. 

I have, however, confirmed that the error only occurs if the ssh server is set with "ChallengeResponse yes" (i.e., uses the ssh "interactive-keyboard" method) rather than "PasswordAuthentication yes".

If I take the ssh server, reconfigure it to do "PasswordAuthentication", sy init and sy connects will then succeed.  Then, if I switch the server back to "ChallengeResponse", I won't be able to do init/connect operations from new working directories, but I will still be able to do an "sy up" on the working directory I set up when the server was in "PasswordAuthentication". 

So it seems the sy init/connect and sy up/down code paths are different enough in the way they invoke JSch such that JSch has different behavior when confronted with the "interactive-keyboard" authentication method.

**Comment by pimotte** [comment] 2015-06-13 10:07
After some tinkering I managed to reproduce your problem and fix it! https://github.com/syncany/syncany-plugin-sftp/commit/81b7c6d8c71d38285308fc5b5992f7ddb546853e works for me. If you can confirm this, I will merge it.

**Comment by vonronne** [comment] 2015-06-15 19:51
That fixes it for me.  Thanks.

**Comment by pimotte** [comment] 2015-06-16 10:14
Awesome!

Again apologies for this taking so long, especially given the great information you provided. Bug reports like these are so extremely helpful:)

Closed by https://github.com/syncany/syncany-plugin-sftp/pull/5

**Closed by pimotte** 2015-06-16 10:14 UTC
Labels: type:bug, what:plugin

**Comment by vonronne** [comment] 2015-06-16 15:52
No problem.  I'm glad I could be of assistance in improving syncany.
