### ISSUE TITLE
Installers/GUI/CLI give no indication of what is wrong when Java is not installed.

### ISSUE THREAD

**Issue by pimotte** [syncany/syncany#478] opened 2015-05-22 17:58 UTC
This is relevant for all OS's where the gui is launched without use of a command line. At least Windows, probably Mac too?

The launcher should probably give a pop-up indicating the user needs to install Java.

**Comment by cr0** [comment] 2015-05-22 18:02
Gradle macappbundle, which we use, is actually generating an appropriate error measage.

**Comment by pimotte** [comment] 2015-12-01 19:04
Including #526. The mac (CLI) homebrew version apperently does not enough pre-checking to load properly.

**Comment by binwiederhier** [comment] 2015-12-13 19:57
Duplicate of https://github.com/syncany/syncany/issues/508

**Closed by binwiederhier** 2015-12-13 19:57 UTC
Labels: prio:low, status:help-needed, type:enhancement, what:gui
