### ISSUE TITLE
High CPU load: syncany in trouble?

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#422] opened 2015-03-27 18:41 UTC
$ sy daemon status
Checking daemon: syncanyd running (pid 2407).

$ ps -p 2407 -o %cpu,%mem,cmd
%CPU %MEM CMD
 210 11.3 java -Dfile.encoding=utf-8 -Xmx512M -classpath /home/kudret/.config/syncany/plugins/lib/*:/usr/share/syncany/lib/bcpkix-jdk15on-1.51.jar:/usr/share/syncany/lib/bcprov-j

Top reports slightly differently, around 320% and this is a quad-core machine. 

$ date
Fri Mar 27 14:37:02 EDT 2015

$ ls -l ~/.config/syncany/logs/
total 95208
-rw-rw-r-- 1 kudret kudret 22424984 Mar 27 10:47 syncany.log.0
-rw-rw-r-- 1 kudret kudret    45544 Mar 23 13:54 syncany.log.0.1
-rw-rw-r-- 1 kudret kudret        0 Mar 23 23:05 syncany.log.0.lck
-rw-rw-r-- 1 kudret kudret 25000057 Mar 24 21:24 syncany.log.1
-rw-rw-r-- 1 kudret kudret 25000168 Mar 24 02:40 syncany.log.2
-rw-rw-r-- 1 kudret kudret 25000419 Mar 23 23:30 syncany.log.3

Appears like log.0 was not updated for a long time, although syncany is clearly working on something according to the cpu load.

**Comment by cr0** [comment] 2015-03-27 23:35
Could you please provide the logs somewhere? Did you try to sync your directories manually?

**Comment by Kudret** [comment] 2015-03-28 14:32
I delayed doing manual sync. I feel like manual sy down/up would put them back into sync... I have three clients: laptop, work and home... On home, daemon was started by syncany gui which was unresponsive to restart, so I did a sy daemon force-stop and sy daemon start.  After a full night, home is still out of sync. I know because there were files added yesterday at work. Of course, work may be having issues, too.

**Comment by Kudret** [comment] 2015-04-10 13:00
Sorry, I do not have this problem currently, therefore cannot provide more info. I had to restart the system due to something else. Feel free to close this. I'll reopen if needed.

**Comment by pimotte** [comment] 2015-04-10 17:49
This problem was (as many others) by memory usage. If I recall correctly, you changed the maxMemory at the advice of someone else in the IRC channel, right? (Closing this anyway for now.)

**Comment by pimotte** [comment] 2015-04-10 17:50
Actually, since I want to be able to check some of the problems we were having earlier once we fixed the memory issues, I'll leave this open as a reminder.

**Comment by binwiederhier** [comment] 2015-05-12 22:00
This is a duplicate of #425 

I have experienced the exact same thing in the past, but with the latest snapshot 0.4.6 I haven't had any issues. We're gonna keep this open for a few weeks and revisit it to see if the issue reappears.

**Comment by mihaisecasiu** [comment] 2015-08-25 12:19
I also have this problem. Syncany is a lot of times using over 200% cpu on a quad core machine. It's always around 100% when it's not actually syncing anything ( the "All files in sync" status in the tray ? ) . I'm using syncany 0.4.6 on OSX Yosemite. I have 8 folders, all using the SFTP plugin. Some of the folders have a few thousand files in them. The largest has over 87000 files. For this one I'm seeing the status as "Downloading database 1/1" frequently. It's also using about 1.5Gb of memory constantly.

**Comment by pimotte** [comment] 2015-11-08 01:03
We have made a lot of memory related improvements, and will be releasing the last of those shortly. If you still experience issues after 0.4.7, feel free to reopen this or open a new issue.

**Closed by pimotte** 2015-11-08 01:03 UTC
Labels: prio:high, status:help-needed, type:bug
