### ISSUE TITLE
GUI crashes when only one file exists in History browser and slider gets moved

### ISSUE THREAD

**Issue by Powersurge** [syncany/syncany#389] opened 2015-02-26 03:43 UTC
I just installed the latest Syncany+GUI. First, I created a text file in the sync folder. Then I opened the history browser.  It showed the text file that I created.  I then tried moving the slider tool at the top and the GUI crashed. I restarted the GUI and tried repeating the above steps and it crashed again. Perhaps the simplest solution would be to disable the slider tool if only one file with no changes to it exists.

**Comment by pimotte** [comment] 2015-02-26 15:01
Thanks for your bugreport. I have reproduced this, below is a stacktrace.

```
26-2-15 15:59:43.339 | MainPanel       | main           | INFO : Main: Date slider value changed to null; setting timer to refresh views in 800ms ...
26-2-15 15:59:43.344 | CommandLineClie | main           | SEVE : Command org.syncany.cli.GuiCommand@791a9134 FAILED. 
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Date to format must not be null.))
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.operations.gui.GuiOperation.startEventDispatchLoop(GuiOperation.java:206)
	at org.syncany.operations.gui.GuiOperation.execute(GuiOperation.java:99)
	at org.syncany.cli.GuiCommand.execute(GuiCommand.java:48)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Date to format must not be null.)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.gui.history.HistoryDialog.open(HistoryDialog.java:102)
	at org.syncany.gui.tray.TrayIcon$2.run(TrayIcon.java:152)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Date to format must not be null.
	at org.ocpsoft.prettytime.PrettyTime.format(PrettyTime.java:245)
	at org.syncany.gui.history.MainPanel$6.run(MainPanel.java:279)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	... 16 more
```

**Comment by pimotte** [comment] 2015-03-07 12:58
https://github.com/syncany/syncany-plugin-gui/commit/e5b76cd4af22b291394841cb765218d299ee4254
should fix this. Once the build finishes you could try out the new build by installing a snapshot `sy plugin install gui --snapshot` 

Thanks again:)

(I'm closing this, as the fix works for me, feel free to reopen if you run into anything.)

**Closed by pimotte** 2015-03-07 12:58 UTC
Labels: prio:high, size:small, status:help-needed, type:bug, what:gui
