### ISSUE TITLE
Initial connect to remote repository should check, not sync

### ISSUE THREAD

**Issue by hdijkema** [syncany/syncany#355] opened 2015-01-26 09:16 UTC
I think with the initial connection to the remote repository, syncany should check weather the repository is sane and can be used, not synchronize all the way. With a large repository, e.g. multiple GB, syncing will take a very long time.

**Comment by pimotte** [comment] 2015-01-26 10:12
Can you be a bit more specific? As far as I know 'syncany init' does not sync.

**Comment by cr0** [comment] 2015-01-26 16:56
[`InitOperation`](https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/operations/init/InitOperation.java) does not run a down operation and [`ConnectOperation`](https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/operations/init/ConnectOperation.java) only downloads the tiny repo master file as far as I can see.

**Comment by hdijkema** [comment] 2015-01-27 01:05
It is when an other sync is running simultaneously that the dialog for creating a new syncany folder won't finish until this other sync has been finished.

**Comment by pimotte** [comment] 2015-01-27 09:28
Reproduced, this is a duplicate of #315. Adding additional information in that issue now.

**Closed by pimotte** 2015-01-27 09:28 UTC
