### ISSUE TITLE
WebDAV HTTPS using Java 1.8.0_31 on Mac OS X

### ISSUE THREAD

**Issue by flyover** [syncany/syncany#435] opened 2015-04-06 14:49 UTC
I have checked the connection via Finder -> Go -> Connect To Server... for both HTTP and HTTPS.

This issue may be related to this.
http://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0

```
$ nano .syncany/config.xml
<url>http://...</url>

$ sy down
Sync down skipped, no remote changes.

$ nano .syncany/config.xml
<url>https://...</url>

$ sy down
Checking remote changes ...Error: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
       Refer to help page using '--help'.

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by binwiederhier** [comment] 2015-04-06 14:51
Duplicate of https://github.com/syncany/syncany/issues/406

**Comment by binwiederhier** [comment] 2015-07-11 12:03
The duplicate issue #406 has been closed. It is most likely a misconfigured server issue and we are not able to implement a workaround, since this would have to be done in our WebDAV library "Sardine"; also see https://github.com/syncany/syncany/issues/406#issuecomment-78232726.

Closing this issue.

**Closed by binwiederhier** 2015-07-11 12:03 UTC
