### ISSUE TITLE
Error: Cannot create new connection; database down?

### ISSUE THREAD

**Issue by tgharib** [syncany/syncany#476] opened 2015-05-21 00:51 UTC
[owner@Taha-PC Box]$ syncany down
Error: Cannot create new connection; database down?
       Refer to help page using '--help'.

[owner@Taha-PC Box]$ syncany down -d
debug
Application version: 0.4.5-alpha
20-5-15 20:49:35.630 | CommandLineClie | main           | INFO : Application version: 0.4.5-alpha
20-5-15 20:49:35.638 | org.syncany.plu | main           | FINE : Validating required fields
20-5-15 20:49:35.642 | TransferManager | main           | INFO : Building WebdavTransferManager from config 'Box' ...
20-5-15 20:49:35.643 | TransferManager | main           | INFO : - With feature Retriable
20-5-15 20:49:35.643 | TransferManager | main           | FINE : - Checking if selected features supported ...
20-5-15 20:49:35.646 | TransferManager | main           | FINE : - Checking for duplicate features ...
20-5-15 20:49:35.647 | TransferManager | main           | FINE : - Checking required feature TransactionAware in WebdavTransferManager ...
20-5-15 20:49:35.649 | TransferManager | main           | FINE : - Checking required feature Retriable in WebdavTransferManager ...
20-5-15 20:49:35.651 | TransferManager | main           | FINE : - Wrapping TransferManager WebdavTransferManager in RetriableFeatureTransferManager
20-5-15 20:49:35.651 | org.syncany.plu | main           | FINE : Validating required fields
20-5-15 20:49:35.652 | TransferManager | main           | INFO : Building WebdavTransferManager from config 'Box' ...
20-5-15 20:49:35.652 | TransferManager | main           | INFO : - With feature Retriable
20-5-15 20:49:35.652 | TransferManager | main           | INFO : - With feature PathAware
20-5-15 20:49:35.653 | TransferManager | main           | INFO : - With feature TransactionAware
20-5-15 20:49:35.655 | TransferManager | main           | FINE : - Checking if selected features supported ...
20-5-15 20:49:35.655 | TransferManager | main           | FINE : - Checking for duplicate features ...
20-5-15 20:49:35.655 | TransferManager | main           | FINE : - Checking required feature TransactionAware in WebdavTransferManager ...
20-5-15 20:49:35.656 | TransferManager | main           | FINE : - Checking required feature Retriable in WebdavTransferManager ...
20-5-15 20:49:35.656 | TransferManager | main           | FINE : - Wrapping TransferManager WebdavTransferManager in RetriableFeatureTransferManager
20-5-15 20:49:35.656 | TransferManager | main           | INFO : - SKIPPING unsupported optional feature PathAware
20-5-15 20:49:35.656 | TransferManager | main           | FINE : - Wrapping TransferManager RetriableFeatureTransferManager in TransactionAwareFeatureTransferManager
20-5-15 20:49:35.661 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
20-5-15 20:49:35.939 | hsqldb.db.HSQLD | main           | INFO : dataFileCache open start
20-5-15 20:49:35.940 | hsqldb.db.HSQLD | main           | INFO : data file was saved but inc backup exists - restoring
20-5-15 20:49:35.941 | hsqldb.db.HSQLD | main           | SEVE : DataFileCache.restoreBackupIncremental
java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at org.hsqldb.persist.RAFileSimple.read(Unknown Source)
	at org.hsqldb.persist.RAShadowFile.restoreFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.open(Unknown Source)
	at org.hsqldb.persist.Log.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.newStore(Unknown Source)
	at org.hsqldb.persist.PersistentStoreCollectionDatabase.getStore(Unknown Source)
	at org.hsqldb.Table.getRowStore(Unknown Source)
	at org.hsqldb.TableBase.isEmpty(Unknown Source)
	at org.hsqldb.TableWorks.addIndex(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
20-5-15 20:49:35.943 | hsqldb.db.HSQLD | main           | SEVE : DataFileCache.open
org.hsqldb.HsqlException: java.io.EOFException
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.open(Unknown Source)
	at org.hsqldb.persist.Log.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.newStore(Unknown Source)
	at org.hsqldb.persist.PersistentStoreCollectionDatabase.getStore(Unknown Source)
	at org.hsqldb.Table.getRowStore(Unknown Source)
	at org.hsqldb.TableBase.isEmpty(Unknown Source)
	at org.hsqldb.TableWorks.addIndex(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at org.hsqldb.persist.RAFileSimple.read(Unknown Source)
	at org.hsqldb.persist.RAShadowFile.restoreFile(Unknown Source)
	... 37 more
20-5-15 20:49:35.944 | hsqldb.db.HSQLD | main           | FINE : dataFileCache file closed
20-5-15 20:49:35.945 | hsqldb.db.HSQLD | main           | WARN : file input/output errorerror org.hsqldb.HsqlException: java.io.EOFException opening file - file /home/owner/Desktop/Box/.syncany/db/local.db.data in statement [CREATE INDEX IDX_DATABASEVERSION_STATUS ON PUBLIC.DATABASEVERSION(STATUS)]
org.hsqldb.HsqlException: file input/output errorerror org.hsqldb.HsqlException: java.io.EOFException opening file - file /home/owner/Desktop/Box/.syncany/db/local.db.data
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.open(Unknown Source)
	at org.hsqldb.persist.Log.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.newStore(Unknown Source)
	at org.hsqldb.persist.PersistentStoreCollectionDatabase.getStore(Unknown Source)
	at org.hsqldb.Table.getRowStore(Unknown Source)
	at org.hsqldb.TableBase.isEmpty(Unknown Source)
	at org.hsqldb.TableWorks.addIndex(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: org.hsqldb.HsqlException: java.io.EOFException
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	... 35 more
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at org.hsqldb.persist.RAFileSimple.read(Unknown Source)
	at org.hsqldb.persist.RAShadowFile.restoreFile(Unknown Source)
	... 37 more
20-5-15 20:49:35.946 | hsqldb.db.HSQLD | main           | WARN : Script processing failure
org.hsqldb.HsqlException: error in script file line: /home/owner/Desktop/Box/.syncany/db/local.db 39
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: org.hsqldb.HsqlException: file input/output errorerror org.hsqldb.HsqlException: java.io.EOFException opening file - file /home/owner/Desktop/Box/.syncany/db/local.db.data
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.open(Unknown Source)
	at org.hsqldb.persist.Log.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.newStore(Unknown Source)
	at org.hsqldb.persist.PersistentStoreCollectionDatabase.getStore(Unknown Source)
	at org.hsqldb.Table.getRowStore(Unknown Source)
	at org.hsqldb.TableBase.isEmpty(Unknown Source)
	at org.hsqldb.TableWorks.addIndex(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	... 24 more
Caused by: org.hsqldb.HsqlException: java.io.EOFException
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	... 35 more
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at org.hsqldb.persist.RAFileSimple.read(Unknown Source)
	at org.hsqldb.persist.RAShadowFile.restoreFile(Unknown Source)
	... 37 more
20-5-15 20:49:35.947 | hsqldb.db.HSQLD | main           | INFO : Database closed
20-5-15 20:49:36.049 | hsqldb.db.HSQLD | main           | SEVE : could not reopen database
org.hsqldb.HsqlException: error in script file line: /home/owner/Desktop/Box/.syncany/db/local.db 39
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: org.hsqldb.HsqlException: file input/output errorerror org.hsqldb.HsqlException: java.io.EOFException opening file - file /home/owner/Desktop/Box/.syncany/db/local.db.data
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.open(Unknown Source)
	at org.hsqldb.persist.Log.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.newStore(Unknown Source)
	at org.hsqldb.persist.PersistentStoreCollectionDatabase.getStore(Unknown Source)
	at org.hsqldb.Table.getRowStore(Unknown Source)
	at org.hsqldb.TableBase.isEmpty(Unknown Source)
	at org.hsqldb.TableWorks.addIndex(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	... 24 more
Caused by: org.hsqldb.HsqlException: java.io.EOFException
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	... 35 more
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at org.hsqldb.persist.RAFileSimple.read(Unknown Source)
	at org.hsqldb.persist.RAShadowFile.restoreFile(Unknown Source)
	... 37 more
20-5-15 20:49:36.052 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DownCommand@6df97b55 FAILED. 
java.lang.RuntimeException: Cannot create new connection; database down?
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:147)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:84)
	at org.syncany.config.Config.createDatabaseConnection(Config.java:237)
	at org.syncany.database.SqlDatabase.<init>(SqlDatabase.java:75)
	at org.syncany.operations.down.DownOperation.<init>(DownOperation.java:112)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.sql.SQLException: error in script file line: /home/owner/Desktop/Box/.syncany/db/local.db 39
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.syncany.database.DatabaseConnectionFactory.createConnection(DatabaseConnectionFactory.java:127)
	... 9 more
Caused by: org.hsqldb.HsqlException: error in script file line: /home/owner/Desktop/Box/.syncany/db/local.db 39
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderText.readDDL(Unknown Source)
	at org.hsqldb.scriptio.ScriptReaderBase.readAll(Unknown Source)
	at org.hsqldb.persist.Log.processScript(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	... 15 more
Caused by: org.hsqldb.HsqlException: file input/output errorerror org.hsqldb.HsqlException: java.io.EOFException opening file - file /home/owner/Desktop/Box/.syncany/db/local.db.data
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.open(Unknown Source)
	at org.hsqldb.persist.Log.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.getCache(Unknown Source)
	at org.hsqldb.persist.Logger.newStore(Unknown Source)
	at org.hsqldb.persist.PersistentStoreCollectionDatabase.getStore(Unknown Source)
	at org.hsqldb.Table.getRowStore(Unknown Source)
	at org.hsqldb.TableBase.isEmpty(Unknown Source)
	at org.hsqldb.TableWorks.addIndex(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	... 24 more
Caused by: org.hsqldb.HsqlException: java.io.EOFException
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	at org.hsqldb.persist.DataFileCache.restoreBackupIncremental(Unknown Source)
	... 35 more
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at org.hsqldb.persist.RAFileSimple.read(Unknown Source)
	at org.hsqldb.persist.RAShadowFile.restoreFile(Unknown Source)
	... 37 more
Error: Cannot create new connection; database down?
       Refer to help page using '--help'.

**Comment by pimotte** [comment] 2015-05-21 06:06
This is a very serious issue, since it seems like the database system itself is corrupted. Can you supply all the logs you have regarding this repo? If you only synced with the command line, all logs are in Taha-PC Box/.syncany/logs

If you also used the daemon, there will also be logs at ~/.config/syncany/logs.

**Comment by tgharib** [comment] 2015-05-21 18:40
The directory is actually: /home/owner/Desktop/Box/

>If you can reproduce it from a new client, that would be even better.

I'm not sure what you mean here.

[Here are the logs from the daemon](https://mega.co.nz/#!AQR13QjA!DDmuPBVIQZAZeHGcMSzgoWU3-poUqSJgy9vS3KU-D4Y)

[Here are the logs from the terminal](https://mega.co.nz/#!0R5FHJST!nbp8Z6J_pAwRhRFvrVW2h3NiArdmmKYPOaLNW_kXH5g)

**Comment by pimotte** [comment] 2015-05-21 19:11
By reproducing from a new client I mean: doing `sy connect` from a new folder to the existing box location and seeing if the error persists when performing down and up.

The issue seems to go back to this time:
     19-5-15 15:58:50.806 | hsqldb.db.HSQLD | main           | INFO : dataFileCache commit start

The database commit starts, but never ends. Can you recall a sudden shutdown at this time?

**Comment by tgharib** [comment] 2015-05-21 19:25
>Can you recall a sudden shutdown at this time?

Yes, I do actually. That was the day when I discovered the [Magic SysRq key](http://en.wikipedia.org/wiki/Magic_SysRq_key) and I invoked a reboot using ALT+PRINT SCREEN+REISUB. It should be noted that I also have another repo over at /home/owner/Desktop/Files/ but that still seems to be working fine.

Do you think it is possible in the future to make some sort of self-correction? Maybe like how my ext4 partition repairs itself after the reboot?

**Comment by tgharib** [comment] 2015-05-21 19:40
Oh, I just realized the repo still works on my laptop. It just doesn't work on my desktop. So I suppose I should close this issue?

**Comment by pimotte** [comment] 2015-05-21 20:03
Well, there is a reason a SysRq reboot is only marginally better than a hard shutdown:P

Connecting a new repo from your desktop should leave you with a functioning one there. 

With regards to the self-correction mechanism, I'll make a seperate issue to discuss that. It's kind of tricky since this seems to be a bug in HSQLDB. Feel free to close this one, thanks for the report:)

**Closed** 2015-05-21 20:12 UTC
Labels: prio:high, status:help-needed, type:bug, what:core
