### ISSUE TITLE
filenames with invalid character encoding don't sync

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#372] opened 2015-02-04 16:43 UTC
It would be nice to have them synced. If not possible, perhaps sy status could report them in a different way. Currently it reports them as "?" Otherwise user may not be sure if rest of the files are synced just fine. I am not sure if all files with valid filenames were synced when this problem happened.

In my case problem filenames were encoded windows-1254, below command fixed the issue for me:
convmv -r --notest -f windows-1254 -t UTF-8 <my_sync_dir>

**Comment by binwiederhier** [comment] 2015-02-05 09:37
@Kudret Did your file browser (Nautilus, Nemo, ...) show the filenames correctly? Did you copy them from a Windows machine?

Since this is a general character encoding issue, I think it's worth investigating this a bit more. Thanks for reporting that. Any experts on file name encodings out there? My file system / encoding knowledge is unfortunately rather limited.

Tasks
- [ ] Investigate the problem
- [ ] Reproduce the situation

General questions / random thoughts / mumblings:
- I presume the encoding of the filename is part of the filesystem header? Or does the filesystem not know at all in which encoding filenames are stored? 
- If the FS doesn't know, the OS just uses the default locale to when interpreting them. 
- So what about USB drives then, or drives that are attached to another system?! I think the FS must know the encoding of the filename....

**Comment by binwiederhier** [comment] 2015-02-05 09:38
@Kudret Can you provide more information? 
- Screenshots of the filename in the file manager
- Screenshots of the Syncany command line
- Log files

**Comment by Kudret** [comment] 2015-02-05 15:04
Here is a screenshot:
![screenshot from 2015-02-05 10 03 14](https://cloud.githubusercontent.com/assets/4098266/6062496/48103084-ad1e-11e4-9c54-1173246d2e24.png)

**Comment by Kudret** [comment] 2015-02-05 15:05
Command line log: 
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir/Master]81 % sy status 
? Working Dir/Master                 
? Working Dir/Master/�SYM les kudret.url
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir/Master]82 % sy up
A Working Dir/Master                 
Sync up finished.
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir/Master]83 % sy status 
? Working Dir/Master/�SYM les kudret.url
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir/Master]84 %

**Comment by Kudret** [comment] 2015-02-05 15:39
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]97 % sy status --log=/tmp/1.log
? Working Dir/Master                 
? Working Dir/Master/�SYM les kudret.url
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]98 % less /tmp/1.log.0 
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]99 % sy up --log=/tmp/2.log
A Working Dir/Master                 
Sync up finished.
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]100 % less /tmp/2.log.0
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]101 % sy status --log=/tmp/3.log
? Working Dir/Master/�SYM les kudret.url
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]102 % cat /tmp/2.log.0
5-2-15 10:30:21.854 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Registering StatusCommand (org.syncany.cli.StatusCommand@4faa65fe) ...
5-2-15 10:30:21.885 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
5-2-15 10:30:22.252 | UpOperation     | main           | INFO : 
5-2-15 10:30:22.252 | UpOperation     | main           | INFO : Running 'Sync up' at client mxKzitVfuURqSnMDWTyo ...
5-2-15 10:30:22.252 | UpOperation     | main           | INFO : --------------------------------------------
5-2-15 10:30:22.253 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpStartSyncExternalEvent (org.syncany.operations.daemon.messages.UpStartSyncExternalEvent@50c3b436) ...
5-2-15 10:30:22.257 | StatusOperation | main           | INFO : 
5-2-15 10:30:22.257 | StatusOperation | main           | INFO : Running 'Status' at client mxKzitVfuURqSnMDWTyo ...
5-2-15 10:30:22.257 | StatusOperation | main           | INFO : --------------------------------------------
5-2-15 10:30:22.257 | StatusOperation | main           | INFO : Querying current file tree from database ...
5-2-15 10:30:22.257 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusStartSyncExternalEvent (org.syncany.operations.daemon.messages.StatusStartSyncExternalEvent@7a6a25ab) ...
5-2-15 10:30:28.605 | StatusOperation | main           | INFO : Analyzing local folder /local-ssd/kudo/Personal/piHD ...
5-2-15 10:30:34.161 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusEndSyncExternalEvent (org.syncany.operations.daemon.messages.StatusEndSyncExternalEvent@4645a73) ...
5-2-15 10:30:34.162 | AbstractTransfe | main           | INFO : Looking for other running remote operations ...
5-2-15 10:30:34.162 | SftpTransferMan | main           | INFO : SFTP client connecting to pi.example.com:22 ...
5-2-15 10:30:34.162 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /home/kudo/.ssh/id_rsa
5-2-15 10:30:35.524 | LsRemoteOperati | main           | INFO : 
5-2-15 10:30:35.524 | LsRemoteOperati | main           | INFO : Running 'Remote Status' at client mxKzitVfuURqSnMDWTyo ...
5-2-15 10:30:35.524 | LsRemoteOperati | main           | INFO : --------------------------------------------
5-2-15 10:30:35.525 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteStartSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteStartSyncExternalEvent@4e5bf0a9) ...
5-2-15 10:30:35.528 | LsRemoteOperati | main           | INFO : Retrieving remote database list.
5-2-15 10:30:35.683 | SftpTransferMan | main           | INFO : Cannot create instance of DatabaseRemoteFile for file cleanup-1; maybe invalid file name pattern. Ignoring file.
5-2-15 10:30:35.832 | LsRemoteOperati | main           | INFO : - Remote database database-VHzIjUorJDDzpqfLgDEL-0000000009 is already known (in local database). Ignoring.
5-2-15 10:30:35.833 | LsRemoteOperati | main           | INFO : - Remote database database-mxKzitVfuURqSnMDWTyo-0000000002 is already known (in local database). Ignoring.
5-2-15 10:30:35.833 | LsRemoteOperati | main           | INFO : - Remote database database-mxKzitVfuURqSnMDWTyo-0000000003 is already known (in local database). Ignoring.
5-2-15 10:30:35.833 | LsRemoteOperati | main           | INFO : - Remote database database-VHzIjUorJDDzpqfLgDEL-0000000007 is already known (in local database). Ignoring.
5-2-15 10:30:35.833 | LsRemoteOperati | main           | INFO : - Remote database database-mxKzitVfuURqSnMDWTyo-0000000004 is already known (in local database). Ignoring.
5-2-15 10:30:35.833 | LsRemoteOperati | main           | INFO : - Remote database database-VHzIjUorJDDzpqfLgDEL-0000000008 is already known (in local database). Ignoring.
5-2-15 10:30:35.833 | LsRemoteOperati | main           | INFO : - Remote database database-INsyGhiYdSsXaYALRjPf-0000000001 is already known (in local database). Ignoring.
5-2-15 10:30:35.834 | LsRemoteOperati | main           | INFO : - Remote database database-VHzIjUorJDDzpqfLgDEL-0000000010 is already known (in local database). Ignoring.
5-2-15 10:30:35.834 | LsRemoteOperati | main           | INFO : - Remote database database-INsyGhiYdSsXaYALRjPf-0000000003 is already known (in local database). Ignoring.
5-2-15 10:30:35.834 | LsRemoteOperati | main           | INFO : - Remote database database-INsyGhiYdSsXaYALRjPf-0000000002 is already known (in local database). Ignoring.
5-2-15 10:30:35.834 | LsRemoteOperati | main           | INFO : - Remote database database-VHzIjUorJDDzpqfLgDEL-0000000011 is already known (in local database). Ignoring.
5-2-15 10:30:35.838 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteEndSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteEndSyncExternalEvent@6d37de6) ...
5-2-15 10:30:35.839 | UpOperation     | main           | INFO : No remote changes, ready to upload.
5-2-15 10:30:35.839 | ActionFileHandl | main           | INFO : Starting action for RemoteFile[name=action-up-mxKzitVfuURqSnMDWTyo-1423150221879] ...
5-2-15 10:30:35.839 | ActionFileHandl | main           | INFO : Uploading action file: RemoteFile[name=action-up-mxKzitVfuURqSnMDWTyo-1423150221879]
5-2-15 10:30:35.840 | SftpTransferMan | main           | INFO : SFTP client connecting to pi.example.com:22 ...
5-2-15 10:30:35.841 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /home/kudo/.ssh/id_rsa
5-2-15 10:30:36.616 | SftpTransferMan | main           | INFO : SFTP: Uploading /tmp/syncany-action-740369549801101244.tmp to temp file /home/kudret/piHD/temp-action-up-mxKzitVfuURqSnMDWTyo-1423150221879
5-2-15 10:30:36.676 | SftpTransferMan | main           | INFO : SFTP: Renaming temp file /home/kudret/piHD/temp-action-up-mxKzitVfuURqSnMDWTyo-1423150221879 to file /home/kudret/piHD/actions/action-up-mxKzitVfuURqSnMDWTyo-1423150221879
5-2-15 10:30:36.706 | ActionFileHandl | main           | INFO : Scheduling action renewal task for every 2 minutes, for RemoteFile[name=action-up-mxKzitVfuURqSnMDWTyo-1423150221879] ...
5-2-15 10:30:36.707 | SftpTransferMan | main           | INFO : SFTP client connecting to pi.example.com:22 ...
5-2-15 10:30:36.707 | SftpTransferMan | main           | INFO : SFTP: Using pubkey authentication with key /home/kudo/.ssh/id_rsa
5-2-15 10:30:37.562 | TransactionAwar | main           | INFO : Done rolling back previous transactions.
5-2-15 10:30:42.629 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpIndexStartSyncExternalEvent (org.syncany.operations.daemon.messages.UpIndexStartSyncExternalEvent@7494fa66) ...
5-2-15 10:30:42.629 | FileVersionComp | main           | INFO :      - [DELETED]: Local file DIFFERS from file version, actual file is NULL, for file Working Dir/Master
5-2-15 10:30:42.632 | Indexer         | main           | INFO :    * Added file version:    FileVersion [version=1, path=Working Dir/Master, type=FOLDER, status=NEW, size=36, lastModified=Thu Feb 05 09:04:49 EST 2015, linkTarget=null, checksum=null, updated=Thu Feb 05 10:30:42 EST 2015, posixPermissions=rwxr-xr-x, dosAttributes=--a-]
5-2-15 10:30:42.632 | Indexer         | main           | INFO :      based on file version: null
5-2-15 10:30:42.632 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpIndexChangesDetectedSyncExternalEvent (org.syncany.operations.daemon.messages.UpIndexChangesDetectedSyncExternalEvent@13ddcfef) ...
5-2-15 10:30:42.633 | Indexer         | main           | INFO :    * NOT ADDING because file has VANISHED (exists = false) or is LOCKED (locked = true).
5-2-15 10:30:42.633 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpIndexEndSyncExternalEvent (org.syncany.operations.daemon.messages.UpIndexEndSyncExternalEvent@641a6f0) ...
5-2-15 10:30:42.846 | UpOperation     | main           | INFO : Last vector clock was: (INsyGhiYdSsXaYALRjPf3,VHzIjUorJDDzpqfLgDEL10,mxKzitVfuURqSnMDWTyo3)
5-2-15 10:30:42.847 | UpOperation     | main           | INFO : Uploading new multichunks ...
5-2-15 10:30:42.849 | UpOperation     | main           | INFO : No DIRTY data found in database (no dirty databases); Nothing to do here.
5-2-15 10:30:42.851 | UpOperation     | main           | INFO : Saving local delta database, version mxKzitVfuURqSnMDWTyo/(INsyGhiYdSsXaYALRjPf3,VHzIjUorJDDzpqfLgDEL10,mxKzitVfuURqSnMDWTyo4)/T=1423150242847 to file /local-ssd/kudo/Personal/piHD/.syncany/cache/database-mxKzitVfuURqSnMDWTyo-0000000005 ... 
5-2-15 10:30:42.851 | UpOperation     | main           | INFO : - Saving database to /local-ssd/kudo/Personal/piHD/.syncany/cache/database-mxKzitVfuURqSnMDWTyo-0000000005 ...
5-2-15 10:30:42.862 | UpOperation     | main           | INFO : - Uploading local delta database file ...
5-2-15 10:30:42.862 | UpOperation     | main           | INFO : - Uploading /local-ssd/kudo/Personal/piHD/.syncany/cache/database-mxKzitVfuURqSnMDWTyo-0000000005 to RemoteFile[name=database-mxKzitVfuURqSnMDWTyo-0000000005] ...
5-2-15 10:30:42.862 | RemoteTransacti | main           | INFO : - Adding file to TX for UPLOAD: /local-ssd/kudo/Personal/piHD/.syncany/cache/database-mxKzitVfuURqSnMDWTyo-0000000005 -> Temp. remote file: RemoteFile[name=temp-eiYfi-database-mxKzitVfuURqSnMDWTyo-0000000005], final location: RemoteFile[name=database-mxKzitVfuURqSnMDWTyo-0000000005]
5-2-15 10:30:42.865 | UpOperation     | main           | INFO : Adding shutdown hook (to allow resuming the upload) ...
5-2-15 10:30:42.865 | RemoteTransacti | main           | INFO : Starting TX.commit() ...
5-2-15 10:30:42.879 | RemoteTransacti | main           | INFO : Wrote transaction manifest to temporary file: /local-ssd/kudo/Personal/piHD/.syncany/cache/temp-transaction-3403167222295895605.tmp
5-2-15 10:30:42.880 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpUploadFileSyncExternalEvent (org.syncany.operations.daemon.messages.UpUploadFileSyncExternalEvent@2028bbf6) ...
5-2-15 10:30:42.880 | RemoteTransacti | main           | INFO : - Uploading remote transaction file RemoteFile[name=transaction-2136f94b] ...
5-2-15 10:30:42.880 | SftpTransferMan | main           | INFO : SFTP: Uploading /local-ssd/kudo/Personal/piHD/.syncany/cache/temp-transaction-3403167222295895605.tmp to temp file /home/kudret/piHD/temp-transaction-2136f94b
5-2-15 10:30:50.202 | SftpTransferMan | main           | INFO : SFTP: Renaming temp file /home/kudret/piHD/temp-transaction-2136f94b to file /home/kudret/piHD/transactions/transaction-2136f94b
5-2-15 10:30:50.232 | RemoteTransacti | main           | INFO : - Starting to upload data in commit.
5-2-15 10:30:50.233 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpUploadFileInTransactionSyncExternalEvent (org.syncany.operations.daemon.messages.UpUploadFileInTransactionSyncExternalEvent@2bf259da) ...
5-2-15 10:30:50.234 | RemoteTransacti | main           | INFO : - Uploading /local-ssd/kudo/Personal/piHD/.syncany/cache/database-mxKzitVfuURqSnMDWTyo-0000000005 to temp. file RemoteFile[name=temp-eiYfi-database-mxKzitVfuURqSnMDWTyo-0000000005] ...
5-2-15 10:30:50.234 | SftpTransferMan | main           | INFO : SFTP: Uploading /local-ssd/kudo/Personal/piHD/.syncany/cache/database-mxKzitVfuURqSnMDWTyo-0000000005 to temp file /home/kudret/piHD/temp-temp-eiYfi-database-mxKzitVfuURqSnMDWTyo-0000000005
5-2-15 10:30:50.322 | SftpTransferMan | main           | INFO : SFTP: Renaming temp file /home/kudret/piHD/temp-temp-eiYfi-database-mxKzitVfuURqSnMDWTyo-0000000005 to file /home/kudret/piHD/temporary/temp-eiYfi-database-mxKzitVfuURqSnMDWTyo-0000000005
5-2-15 10:30:50.353 | RemoteTransacti | main           | INFO : - Moving temp. file RemoteFile[name=temp-eiYfi-database-mxKzitVfuURqSnMDWTyo-0000000005] to final location RemoteFile[name=database-mxKzitVfuURqSnMDWTyo-0000000005] ...
5-2-15 10:30:50.382 | RemoteTransacti | main           | INFO : - Deleting remote transaction file RemoteFile[name=transaction-2136f94b] ...
5-2-15 10:30:50.412 | RemoteTransacti | main           | INFO : END of TX.commmit(): Succesfully committed transaction.
5-2-15 10:30:50.413 | RemoteTransacti | main           | INFO : END of TX.delTemp(): Sucessfully deleted final files.
5-2-15 10:30:50.417 | UpOperation     | main           | INFO : Persisting local SQL database (new database version mxKzitVfuURqSnMDWTyo/(INsyGhiYdSsXaYALRjPf3,VHzIjUorJDDzpqfLgDEL10,mxKzitVfuURqSnMDWTyo4)/T=1423150242847) ...
5-2-15 10:30:50.423 | UpOperation     | main           | INFO : Removing DIRTY database versions from database ...
5-2-15 10:30:51.656 | ActionFileHandl | main           | INFO : Finishing action for RemoteFile[name=action-up-mxKzitVfuURqSnMDWTyo-1423150221879] ...
5-2-15 10:30:51.656 | ActionFileHandl | main           | INFO : Deleting action file: RemoteFile[name=action-up-mxKzitVfuURqSnMDWTyo-1423150221879]
5-2-15 10:30:51.686 | AbstractTransfe | main           | INFO : Cleaning own old action files ...
5-2-15 10:30:51.988 | Cache           | main           | INFO : Cache size okay (508261 KB), no need to clean (keep size is 500 MB)
5-2-15 10:30:51.988 | UpOperation     | main           | INFO : Sync up done.
5-2-15 10:30:51.989 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpEndSyncExternalEvent (org.syncany.operations.daemon.messages.UpEndSyncExternalEvent@ce5988b) ...
[kudo-deb7-64:/home/kudo/Personal/piHD/Working Dir]103 %

**Comment by binwiederhier** [comment] 2015-02-13 06:15
While this is very annoying for the user, I feel that this is a "bad luck" situation. It's not Syncany's fault that the filenames encoding is wrong -- and it's not like Syncany deletes all the files or creates a mess. Due to that, I tend towards not taking any action here. 

I'm closing this issue for now. @cr0 or @pimotte, if you disagree, please re-open.

**Closed by binwiederhier** 2015-02-13 06:15 UTC
Labels: status:help-needed, type:bug, what:core
