### ISSUE TITLE
ftp - unable to create remote repository

### ISSUE THREAD

**Issue by mattdperkins** [syncany/syncany#318] opened 2014-12-26 17:04 UTC
I've been trying to set up syncany to backup to an ftp server, recieving errors each time. 

I was originally using the .11 version that is n the mint ppa, but have now upgraded to .3 version and still receive the same error message.
Here is the output of sy init --debug on a test directory I was trying. If I log into the ftp server using the same credentials I am able to put files with no errors:

```
matt@rse ~/tmp/syncanyremote $ sy init --debug
debug
Application version: 0.3.0-alpha
26-12-14 17:55:56.095 | CommandLineClie | main           | INFO : Application version: 0.3.0-alpha
26-12-14 17:55:56.459 | Plugins         | main           | INFO : - org.syncany.plugins.ftp.FtpTransferPlugin
26-12-14 17:55:56.461 | Plugins         | main           | INFO : - org.syncany.plugins.gui.GuiPlugin
26-12-14 17:55:56.462 | Plugins         | main           | INFO : - org.syncany.plugins.local.LocalTransferPlugin
Choose a storage plugin. Available plugins are: ftp, local
Plugin: ftp

Connection details for ftp connection:
- Hostname: -----------
- Username: ------
- Password (not displayed): 
- Relative path: driveloco/test
- Port (21): 
26-12-14 17:56:27.114 | org.syncany.plu | main           | FINE : Validating required fields
26-12-14 17:56:27.115 | org.syncany.cli | main           | INFO : Settings are FtpTransferSettings[hostname=---------:21, username=-----, path=driveloco/test]
26-12-14 17:56:27.511 | AbstractInitOpe | main           | INFO : 
26-12-14 17:56:27.512 | AbstractInitOpe | main           | INFO : Running 'Init'
26-12-14 17:56:27.512 | AbstractInitOpe | main           | INFO : --------------------------------------------
26-12-14 17:56:27.513 | org.syncany.plu | main           | FINE : Validating required fields
26-12-14 17:56:27.525 | AbstractTransfe | main           | INFO : Performing storage test TM.test() ...
26-12-14 17:56:27.526 | AbstractTransfe | main           | INFO : - Running connect() ...
26-12-14 17:56:27.527 | FtpTransferMana | main           | INFO : FTP client connecting to ---------:21 ...
26-12-14 17:56:27.690 | FtpTransferMana | main           | INFO : testTargetExists: Target exists. Chdir successful.
26-12-14 17:56:27.870 | FtpTransferMana | main           | INFO : testTargetCanWrite: Can write, test file created/deleted successfully.
26-12-14 17:56:28.002 | FtpTransferMana | main           | INFO : testRepoFileExists: Repo file DOES NOT exist: list(repo) DID NOT contain 'syncany' file:
-rwxrwxrwx    1 0        0               0 Dec 26 16:31 test.txt
26-12-14 17:56:28.002 | AbstractInitOpe | main           | INFO : Storage test result ist StorageTestResult [targetExists=true, targetCanConnect=true, targetCanCreate=true, targetCanWrite=true, repoFileExists=false]
26-12-14 17:56:28.002 | AbstractInitOpe | main           | INFO : --> OKAY: Target exists and is writable, but repo doesn't exist. We're good to go!
26-12-14 17:56:28.003 | AbstractInitOpe | main           | INFO : - Connecting to the repo was successful

The password is used to encrypt data on the remote storage.
Choose wisely!

Password (min. 10 chars): 
Confirm: 

WARNING: The password is a bit short. Less than 12 chars are not future-proof!
Are you sure you want to use it (y/n)? y

Creating master key from password (this might take a while) ...
26-12-14 17:56:52.236 | CipherUtil      | main           | FINE : - Creating secret key using PBKDF2WithHmacSHA1 with 1,000,000 rounds, key size 512 bit ...
26-12-14 17:56:58.804 | CipherSession   | main           | FINE : - Created NEW WRITE secret key HmacSHA256, and added to cache, with salt d298dde1849dfd72a37d3047
26-12-14 17:56:58.822 | CipherSession   | main           | FINE : - Created NEW WRITE secret key AES, and added to cache, with salt b93cc0d18273cfc6c9d27cd3
26-12-14 17:56:58.831 | CipherSession   | main           | FINE : - Created NEW WRITE secret key Twofish, and added to cache, with salt 081771cca088cbe29835ac67
26-12-14 17:56:58.854 | CipherSession   | main           | FINE : - Created NEW WRITE secret key HmacSHA256, and added to cache, with salt 949cd814cfc3226f61cb9c03
26-12-14 17:56:58.855 | CipherSession   | main           | FINE : - Created NEW WRITE secret key AES, and added to cache, with salt ef738c00da51f756e14a8dd8
26-12-14 17:56:58.857 | CipherSession   | main           | FINE : - Created NEW WRITE secret key Twofish, and added to cache, with salt 8fa6f3eadd1f32a6a1eb3e06
26-12-14 17:56:58.861 | AbstractInitOpe | main           | INFO : Uploading local repository
26-12-14 17:56:58.861 | FtpTransferMana | main           | INFO : FTP client connecting to ---------:21 ...
26-12-14 17:56:59.038 | FtpTransferMana | main           | INFO : testRepoFileExists: Repo file DOES NOT exist: list(repo) DID NOT contain 'syncany' file:
-rwxrwxrwx    1 0        0               0 Dec 26 16:31 test.txt
26-12-14 17:56:59.138 | FtpTransferMana | main           | INFO : FTP client already connected. Skipping connect().
26-12-14 17:56:59.140 | FtpTransferMana | main           | INFO : FTP: Uploading /home/matt/tmp/syncanyremote/./.syncany/master to temp file /driveloco/test/temp-master
26-12-14 17:56:59.205 | FtpTransferMana | main           | SEVE : Could not upload file /home/matt/tmp/syncanyremote/./.syncany/master to master
java.io.IOException: Error uploading file master
	at org.syncany.plugins.ftp.FtpTransferManager.upload(FtpTransferManager.java:240)
	at org.syncany.operations.init.InitOperation.uploadMasterFile(InitOperation.java:243)
	at org.syncany.operations.init.InitOperation.execute(InitOperation.java:130)
	at org.syncany.Client.init(Client.java:158)
	at org.syncany.cli.InitCommand.execute(InitCommand.java:79)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
26-12-14 17:56:59.212 | CommandLineClie | main           | SEVE : Command org.syncany.cli.InitCommand@5b4bf56d FAILED. 
org.syncany.plugins.transfer.StorageException: Couldn't upload to remote repo. Cleaned local repository.
	at org.syncany.operations.init.InitOperation.cleanLocalRepository(InitOperation.java:205)
	at org.syncany.operations.init.InitOperation.execute(InitOperation.java:136)
	at org.syncany.Client.init(Client.java:158)
	at org.syncany.cli.InitCommand.execute(InitCommand.java:79)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:391)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:381)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:197)
	at org.syncany.Syncany.main(Syncany.java:55)
Caused by: org.syncany.plugins.transfer.StorageException: java.io.IOException: Error uploading file master
	at org.syncany.plugins.ftp.FtpTransferManager.upload(FtpTransferManager.java:256)
	at org.syncany.operations.init.InitOperation.uploadMasterFile(InitOperation.java:243)
	at org.syncany.operations.init.InitOperation.execute(InitOperation.java:130)
	... 6 more
Caused by: java.io.IOException: Error uploading file master
	at org.syncany.plugins.ftp.FtpTransferManager.upload(FtpTransferManager.java:240)
	... 8 more
Error: Couldn't upload to remote repo. Cleaned local repository.
       Refer to help page using '--help'.
```

**Comment by binwiederhier** [comment] 2015-02-19 04:43
@mattdperkins I am unfortunately not able to reproduce this issue on my server. Unless you're able to provide more intel, I'm afraid I can't help with this. 

With that in mind, I'd like to close this issue for now until we get more info. We have other tickets that need attention too. I hope I'm not stepping on your toes here...

**Closed by binwiederhier** 2015-02-19 04:43 UTC
Labels: status:help-needed, type:bug
